##===- tools/Makefile --------------------------------------*- Makefile -*-===##
#
#                     The Cling Interpreter
#
# This file is dual-licensed: you can choose to license it under the University
# of Illinois Open Source License or the GNU Lesser General Public License. See
# LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL := ../../..
DIRS := driver

include $(LEVEL)/Makefile.common
